version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - ballast_network
    command: >
      /bin/sh -c "bundle exec rails db:create db:migrate db:seed && bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=3001 # Ensure React runs on 3001
    networks:
      - ballast_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ballast_library_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ballast_network

volumes:
  pgdata:

networks:
  ballast_network:
    driver: bridge
