{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/books": {
      "get": {
        "summary": "List all books",
        "tags": [
          "Books"
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "books listed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "title": {
                        "type": "string"
                      },
                      "author": {
                        "type": "string"
                      },
                      "genre": {
                        "type": "string"
                      },
                      "isbn": {
                        "type": "string"
                      },
                      "total_copies": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "id",
                      "title",
                      "author",
                      "genre",
                      "isbn",
                      "total_copies"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/books/{id}": {
      "get": {
        "summary": "Show book",
        "tags": [
          "Books"
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "book found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "title": {
                      "type": "string"
                    },
                    "author": {
                      "type": "string"
                    },
                    "genre": {
                      "type": "string"
                    },
                    "isbn": {
                      "type": "string"
                    },
                    "total_copies": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/sign_in": {
      "post": {
        "summary": "Sign in a user",
        "tags": [
          "Authentication"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "user signed in"
          },
          "401": {
            "description": "invalid credentials"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "object",
                    "properties": {
                      "email": {
                        "type": "string"
                      },
                      "password": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "email",
                      "password"
                    ]
                  }
                },
                "redquired": [
                  "user"
                ]
              }
            }
          }
        }
      }
    },
    "/users/sign_out": {
      "delete": {
        "summary": "Sign out a user",
        "tags": [
          "Authentication"
        ],
        "responses": {
          "200": {
            "description": "user signed out"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000"
        }
      }
    }
  ],
  "components": {
    "securitySchemes": {
      "Bearer": {
        "description": "...",
        "type": "apiKey",
        "name": "authorization",
        "in": "header"
      }
    }
  }
}